### PR TITLE
refactor(example): Update example code to use middle name prop.

### PR DESCRIPTION
**Pull request by Borgund**
This pull request includes updates to the `my-component` element to use the `middle` attribute and adjust its usage across various files.

Updates to `my-component` usage:

* `readme.md`: Updated the example usage of `<my-component>` to include the `middle` attribute and adjusted the `last` attribute accordingly.
* `src/index.html`: Modified the `<my-component>` element to include the `middle` attribute.

Test updates:
* `src/components/my-component/my-component.spec.ts`: Updated the test case to include the `middle` attribute for `<my-component>`.

Closes: #139

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by christian-bromann** [comment]
Thanks a lot @Borgund 🙏

**Comment by Borgund** [comment]
No problem, it was bugging me 😄

**Comment by Borgund** [comment]
And a heads up. This is used in a some of your other repos as well. So some tests in those repos might fail after scaffolding a new project: 

https://github.com/search?q=org:ionic-team%20last%3D%22'Don&type=code

**Pull request merged**
