### PR TITLE
fix(): change src barrel file to export all type declarations

### PR DESCRIPTION
**Pull request by tanner-reits**
This commit changes the `index.ts` file auto-generated in the `src` directory to export all exportable declarations from the `component.d.ts` file. This makes for a better developer experience as all types will be automatically exported from the root of output target directories (e.g. custom event types)

## Changed behavior
With this change, everything marked as `export` from the `component.d.ts` file will now be exported from the `index.ts` file. This continues to include the `Components` and `JSX` definitions that were previously exported by name. But, this will now also include any custom events and (soon) types used as a part of custom events.

For instance, if there is a Stencil component with an `@Event()` output:
```ts
export type MyCustomEventType = {
  name: string;
  value: number;
}

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true,
})
export class MyComponent {
  @Event() myEvent: EventEmitter<MyCustomEventType>:

  // All your other component stuff here
}
```

The `component.d.ts` file would generate type definitions such as:
```ts
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentAElement;
} 
```
This type will now be re-exported by the barrel file. In addition, once [this PR](https://github.com/ionic-team/stencil/pull/3612) is merged, the `component.d.ts` file will also re-export the custom event types used in component event emitter definitions so consuming applications can easily use them to define expected metadata structure. So, the `index.ts` file will then also export those types.

## Testing
1. Pull/fork this code to be used as a Stencil project (this is essentially what the "create Stencil" CLI app does when choosing a component starter).
2. Modify the `MyComponent` component to include an `@Event()`definition.
3. Build the project and verify the contents of `dist/types/index.ts` is `export * from './components';`
4. Locally package the build and consume in a separate project.
5. Verify `Components`, `JSX`, and `MyComponentCustomEvent` can all be imported from the package types (i.e. something like `import { Components, JSX, MyComponentCustomEvent} from '@my-test-package/types';`)

### CODE REVIEW

**Comment by tanner-reits** [comment]
This can be merged now, but this change is helpful for an upcoming Stencil PR that deals with exporting custom event types

**Review by alicewriteswrongs — APPROVED** [review]
I'm good w/ it 👍

**Review by rwaskiewicz — CHANGES_REQUESTED** [review]
Code looks good to me.  However I want to add a little more detail to this PR's summary to avoid archaeological issues in the future. @tanner-reits  can you expound on this for me please (and future us)?

1. What types are now going to be exported that weren't previously? Can we give a concrete example?
2. Can you add the steps/methodology followed for testing this PR?

Thanks!

**Review by rwaskiewicz — APPROVED** [review]
Thanks for updating that description! 🔥 🔥 🔥

**Pull request merged**
